version: '3.8'

services: 
  npm:
    container_name: npm
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    expose: 
      - "5001"
    ports:
      - "5002:5001"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - "80:5000"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   restart: always
  #   # networks:
  #   #   - ironman-net

